# UNCOMMENT BELOW LINES FOR DESKTOP
# wallpaper = {
#    monitor = HDMI-A-2
#    path = /home/largor/Pictures/wallpapers/main/walls-catppuccin-mocha-master/astronaut.png
# }
# wallpaper = {
#    monitor = DP-1
#    path = /home/largor/Pictures/wallpapers/main/walls-catppuccin-mocha-master/car-wreck.png
# }


# UNCOMMENT BELOW LINES FOR LAPTOP
# wallpaper {
#    monitor =
#    path = /home/largor/Pictures/wallpapers/main/art/Christ_in_the_Wilderness_-_Ivan_Kramskoy(1920x1080).png
# }
